export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS= 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

export const LOGOUT = 'LOGOUT';

export const GET_NEARBY_USERS = 'GET_NEARBY_USERS';
export const GET_NEARBY_USERS_SUCCESS = 'GET_NEARBY_USERS_SUCCESS';
export const GET_NEARBY_USERS_FAILURE = 'GET_NEARBY_USERS_FAILURE';

export const GET_WATCHLIST_USERS = 'GET_WATCHLIST_USERS';
export const GET_WATCHLIST_USERS_SUCCESS= 'GET_WATCHLIST_USERS_SUCCESS';
export const GET_WATCHLIST_USERS_FAILURE = 'GET_WATCHLIST_USERS_FAILURE';

export const GET_NEW_USERS = 'GET_NEW_USERS';
export const GET_NEW_USERS_SUCCESS = 'GET_NEW_USERS_SUCCESS';
export const GET_NEW_USERS_FAILURE = 'GET_NEW_USERS_FAILURE';

export const GET_TOP_USERS = 'GET_TOP_USERS';
export const GET_TOP_USERS_SUCCESS = 'GET_TOP_USERS_SUCCESS';
export const GET_TOP_USERS_FAILURE = 'GET_TOP_USERS_FAILURE';

export const SEARCH_USERS = 'SEARCH_USERS';
export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS';
export const SEARCH_USERS_FAILURE = 'SEARCH_USERS_FAILURE';

export const EMPTY_SEARCH = 'EMPTY_SEARCH'


export const GET_FILTER_USERS = 'GET_FILTER_USERS';
export const GET_FILTER_USERS_SUCCESS= 'GET_FILTER_USERS_SUCCESS';
export const GET_FILTER_USERS_FAILURE= 'GET_FILTER_USERS_FAILURE';

export const USERS_SET_FLAG = 'USERS_SET_FLAG';

export const REFRESH_USERS= 'REFRESH_USERS';


export const CHANGE_LOCATION = 'CHANGE_LOCATION';
export const CHANGE_LOCATION_SUCCESS = 'CHANGE_LOCATION_SUCCESS';
export const CHANGE_LOCATION_FAILURE = 'CHANGE_LOCATION_FAILURE';

export const DEACTIVATE_ACCOUNT = 'DEACTIVATE_ACCOUNT';
export const DEACTIVATE_ACCOUNT_SUCCESS = 'DEACTIVATE_ACCOUNT_SUCCESS';
export const DEACTIVATE_ACCOUNT_FAILURE = 'DEACTIVATE_ACCOUNT_FAILURE';

export const REACTIVATE_ACCOUNT = 'REACTIVATE_ACCOUNT';
export const REACTIVATE_ACCOUNT_SUCCESS = 'REACTIVATE_ACCOUNT_SUCCESS';
export const REACTIVATE_ACCOUNT_FAILURE = 'REACTIVATE_ACCOUNT_FAILURE';

export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';
export const DELETE_ACCOUNT_FAILURE = 'DELETE_ACCOUNT_FAILURE';

//Gallery
export const GET_GALLERY = 'GET_GALLERY';
export const GET_GALLERY_SUCCESS = 'GET_GALLERY_SUCCESS';
export const GET_GALLERY_FAILURE = 'GET_GALLERY_FAILURE';

export const DELETE_IMAGE_GALLERY = 'DELETE_GALLERY';
export const DELETE_IMAGE_GALLERY_SUCCESS = 'DELETE_GALLERY_SUCCESS';
export const DELETE_IMAGE_GALLERY_FAILURE = 'DELETE_GALLERY_FAILURE';

export const ADD_IMAGE_GALLERY = 'ADD_GALLERY';
export const ADD_IMAGE_GALLERY_SUCCESS = 'ADD_GALLERY_SUCCESS';
export const ADD_IMAGE_GALLERY_FAILURE = 'ADD_GALLERY_FAILURE';
export const ADD_IMAGE_GALLERY_PROCESS = 'ADD_IMAGE_GALLERY_PROCESS';



//Profile

export const LOAD_MY_BLOCK = 'LOAD_MY_BLOCK';
export const LOAD_MY_BLOCK_SUCCESS = 'LOAD_MY_BLOCK_SUCCESS';
export const LOAD_MY_BLOCK_FAILURE = 'LOAD_MY_BLOCK_FAILURE';

export const GET_MY_GALLERY = 'GET_MY_GALLERY';
export const GET_MY_GALLERY_SUCCESS = 'GET_MY_GALLERY_SUCCESS';
export const GET_MY_GALLERY_FAILURE = 'GET_MY_GALLERY_FAILURE';

export const LOAD_PROFILE = 'LOAD_PROFILE';
export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS';
export const LOAD_PROFILE_FAILURE = 'LOAD_PROFILE_FAILURE';

export const UPDATE_PROFILE_IMAGE = 'UPDATE_PROFILE_IMAGE';
export const UPDATE_PROFILE_IMAGE_SUCCESS = 'UPDATE_PROFILE_IMAGE_SUCCESS';
export const UPDATE_PROFILE_IMAGE_FAILURE = 'UPDATE_PROFILE_IMAGE_FAILURE';
export const UPDATE_PROFILE_IMAGE_PROCESS = 'UPDATE_PROFILE_IMAGE_PROCESS'

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const UPDATE_EMAIL_SUCCESS = 'UPDATE_EMAIL_SUCCESS';
export const UPDATE_EMAIL_FAILURE = 'UPDATE_EMAIL_FAILURE';

export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAILURE = 'UPDATE_PASSWORD_FAILURE';

export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';

export const GET_MY_ACCEPTED_COMMENTS = 'GET_MY_ACCEPTED_COMMENTS';
export const GET_MY_ACCEPTED_COMMENTS_SUCCESS = 'GET_MY_ACCEPTED_COMMENTS_SUCCESS';
export const GET_MY_ACCEPTED_COMMENTS_FAILURE = 'GET_MY_ACCEPTED_COMMENTS_FAILURE';



export const DELETE_MY_COMMENT = 'DELETE_MY_COMMENT';
export const DELETE_MY_COMMENT_SUCCESS = 'DELETE_MY_COMMENT_SUCCESS';
export const DELETE_MY_COMMENT_FAILURE = 'DELETE_MY_COMMENT_FAILURE';

export const REPORT_USER_COMMENT = 'REPORT_USER_COMMENT';
export const REPORT_USER_COMMENT_SUCCESS = 'REPORT_USER_COMMENT_SUCCESS';
export const REPORT_USER_COMMENT_FAILURE = 'REPORT_USER_FAILURE';




//Public Profile
export const POST_COMMENT = 'POST_COMMENT';
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';
export const POST_COMMENT_FAILURE = 'POST_COMMENT_FAILURE';

export const CONFIRM_COMMENT = 'CONFIRM_COMMENT';
export const CONFIRM_COMMENT_SUCCESS = 'CONFIRM_COMMENT_SUCCESS';
export const CONFIRM_COMMENT_FAILURE = 'CONFIRM_COMMENT_FAILURE';

export const GET_ACCEPTED_COMMENTS = 'GET_ACCEPTED_COMMENTS';
export const GET_ACCEPTED_COMMENTS_SUCCESS = 'GET_ACCEPTED_COMMENTS_SUCCESS';
export const GET_ACCEPTED_COMMENTS_FAILURE = 'GET_ACCEPTED_COMMENTS_FAILURE';



export const LOAD_PUBLIC_PROFILE = 'LOAD_PUBLIC_PROFILE';
export const LOAD_PUBLIC_PROFILE_SUCCESS = 'LOAD_PUBLIC_PROFILE_SUCCESS';
export const LOAD_PUBLIC_PROFILE_FAILURE = 'LOAD_PUBLIC_PROFILE_FAILURE';

export const BLOCK_USER = 'BLOCK_USER';
export const BLOCK_USER_SUCCESS = 'BLOCK_USER_SUCCESS';
export const BLOCK_USER_FAILURE = 'BLOCK_USER_FAILURE';

export const UNBLOCK_USER = 'UNBLOCK_USER';
export const UNBLOCK_USER_SUCCESS = 'UNBLOCK_USER_SUCCESS';
export const UNBLOCK_USER_FAILURE = 'UNBLOCK_USER_FAILURE';

export const WATCH_USER = 'WATCH_USER';
export const WATCH_USER_SUCCESS = 'WATCH_USER_SUCCESS';
export const WATCH_USER_FAILURE = 'WATCH_USER_FAILURE';

export const UNWATCH_USER = 'UNWATCH_USER';
export const UNWATCH_USER_SUCCESS = 'UNWATCH_USER_SUCCESS';
export const UNWATCH_USER_FAILURE = 'UNWATCH_USER_FAILURE';

export const BONE_USER = 'BONE_USER';
export const BONE_USER_SUCCESS = 'BONE_USER_SUCCESS';
export const BONE_USER_FAILURE = 'BONE_USER_FAILURE';

export const UNBONE_USER = 'UNBONE_USER';
export const UNBONE_USER_SUCCESS = 'UNBONE_USER_SUCCESS';
export const UNBONE_USER_FAILURE = 'UNBONE_USER_FAILURE';

export const REPORT_USER = 'REPORT_USER';
export const REPORT_USER_SUCCESS = 'REPORT_USER_SUCCESS';
export const REPORT_USER_FAILURE = 'REPORT_USER_FAILURE';

export const RATE_USER = 'RATE_USER';
export const RATE_USER_SUCCESS = 'RATE_USER_SUCCESS';
export const RATE_USER_FAILURE = 'RATE_USER_FAILURE';


//App

export const GET_MODIFIABLES = "GET_MODIFIABLES";
export const GET_MODIFIABLES_SUCCESS = "GET_MODIFIABLES_SUCCESS";
export const GET_MODIFIABLES_FAILURE = "GET_MODIFIABLES_FAILURE";


//Filter
export const ENABLE_FILTER = "ENABLE_FILTER";
export const ENABLE_LOCATION = "ENABLE_LOCATION";
export const ENABLE_EYE = "ENABLE_EYE";
export const UPDATE_FILTER = "UPDATE_FILTER";
export const RESET_FILTER = "RESET_FILTER";
export const ENABLE_ONLINE= "ENABLE_ONLINE";

//location
export const SAVE_CURRENT_LOCATION = "SAVE_CURRENT_LOCATION"


//LockCode
export const ENABLE_LOCK = "ENABLE_LOCK";
export const DISABLE_LOCK = "DISABLE_LOCK";

//Chat

export const CREATE_CHATROOM = "CREATE_CHATROOM";
export const CREATE_CHATROOM_SUCCESS = "CREATE_CHATROOM_SUCCESS";
export const CREATE_CHATROOM_FAILURE = "CREATE_CHATROOM_FAILURE";

export const REMOVE_CHATROOM = "REMOVE_CHATROOM";
export const REMOVE_CHATROOM_SUCCESS = "REMOVE_CHATROOM_SUCCESS";
export const REMOVE_CHATROOM_FAILURE = "REMOVE_CHATROOM_FAILURE";

export const GET_CHATROOM_LIST = "GET_CHATROOM_LIST";
export const GET_CHATROOM_LIST_SUCCESS = "GET_CHATROOM_LIST_SUCCESS";
export const GET_CHATROOM_LIST_FAILURE = "GET_CHATROOM_LIST_FAILURE";

export const GET_MESSAGES = "GET_MESSAGES";
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";
export const GET_MESSAGES_FAILURE = "GET_MESSAGES_FAILURE";

export const ADD_USER_TO_CHATROOM = "ADD_USER_TO_CHATROOM";
export const ADD_USER_TO_CHATROOM_SUCCESS = "ADD_USER_TO_CHATROOM_SUCCESS";
export const ADD_USER_TO_CHATROOM_FAILURE = "ADD_USER_TO_CHATROOM_FAILURE";

export const UPLOAD_IMAGE_CHAT = "UPLOAD_IMAGE_CHAT";
export const UPLOAD_IMAGE_CHAT_SUCCESS = "UPLOAD_IMAGE_CHAT_SUCCESS";
export const UPLOAD_IMAGE_CHAT_PROCESS = "UPLOAD_IMAGE_CHAT_PROCESS";
export const UPLOAD_IMAGE_CHAT_FAILURE = "UPLOAD_IMAGE_CHAT_FAILURE";

export const UPLOAD_AUDIO_CHAT = "UPLOAD_IMAGE_CHAT";
export const UPLOAD_AUDIO_CHAT_SUCCESS = "UPLOAD_IMAGE_CHAT_SUCCESS";
export const UPLOAD_AUDIO_CHAT_PROCESS = "UPLOAD_IMAGE_CHAT_PROCESS";
export const UPLOAD_AUDIO_CHAT_FAILURE = "UPLOAD_IMAGE_CHAT_FAILURE";

export const APPEAR_OFFLINE = "APPEAR_OFFLINE";
export const APPEAR_OFFLINE_SUCCESS = "APPEAR_OFFLINE_SUCCESS";
export const APPEAR_OFFLINE_FAILURE = "APPEAR_OFFLINE_FAILURE";

export const APPEAR_ONLINE = "APPEAR_ONLINE";
export const APPEAR_ONLINE_SUCCESS = "APPEAR_ONLINE_SUCCESS";
export const APPEAR_ONLINE_FAILURE = "APPEAR_ONLINE_FAILURE";

export const UNLOCK_ALBUM = "UNLOCK_ALBUM";
export const UNLOCK_ALBUM_SUCCESS = "UNLOCK_ALBUM_SUCCESS";
export const UNLOCK_ALBUM_FAILURE = "UNLOCK_ALBUM_FAILURE";

export const LOCK_ALBUM = "LOCK_ALBUM";
export const LOCK_ALBUM_SUCCESS = "LOCK_ALBUM_SUCCESS";
export const LOCK_ALBUM_FAILURE = "LOCK_ALBUM_FAILURE";

export const GET_MEDIA_HISTORY = "GET_MEDIA_HISTORY";
export const GET_MEDIA_HISTORY_SUCCESS = "GET_MEDIA_HISTORY_SUCCESS";
export const GET_MEDIA_HISTORY_FAILURE = "GET_MEDIA_HISTORY_FAILURE";

